version: "3.7"
networks:
  twfy:
services:
  webhost:
    # image: php:7.4.33-apache-bullseye
    image: twfy-app
    networks:
      - twfy
    ports:
      - 80:80
    volumes:
      - ./www:/var/www
      - ./conf:/var/conf # not a great location, but it works
      
