version: "3.7"
networks:
  twfy:
services:
  webhost:
    # image: php:7.4.33-apache-bullseye
    image: twfy-app
    networks:
      - twfy
    ports:
      - 80:80
    volumes:
      - ./www:/var/www
      - ./conf:/var/conf # not a great location, but it works
  mysql:
    image: mysql:8.4.7
    ports:
      - 3306:3306
    networks:
      - twfy
    environment:
      MYSQL_ROOT_PASSWORD: examplepassword
      MYSQL_DATABASE: twfy
      MYSQL_USER: twfyuser
      MYSQL_PASSWORD: twfypass
    volumes:
      - ./_mysqldata:/var/lib/mysql